name: kivusoft_test
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  awesome_dialog: ^3.2.0
  flutter_easyloading: ^3.0.5
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  url_launcher: ^6.2.4
  icons_plus: ^5.0.0
  google_fonts: ^6.1.0
  mask_text_input_formatter: ^2.8.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  lottie: ^3.0.0
  file_picker: ^6.1.1
  crop_image: ^1.0.12
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  flutter_corner_banner: ^1.0.1
  timeline_tile: ^2.0.0
  flutter_hooks: ^0.20.5
  badges: ^3.1.2
  contextmenu: ^3.0.0
  printing: ^5.11.1
  sqflite_common_ffi_web: ^0.4.2+3
  logger: ^2.0.2+1
  # image_compression_flutter: ^1.0.3
  image_compression_flutter:
    path: ./plugin/image_compression_flutter-main
  flutter_native_splash: ^2.3.10
  icons_launcher: ^2.1.7
  rename_app: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  background_image: "assets/images/splash.jpg"
